# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://atlas.hashicorp.com/search.
  config.vm.box = "debian/contrib-buster64"

  # Create a private network, which allows host-only access to the machine
  # using a specific IP.
  # config.vm.network "private_network", ip: "192.168.33.10"

  # Create a public network, which generally matched to bridged network.
  # Bridged networks make the machine appear as another physical device on
  # your network.
  # config.vm.network "public_network"

  # Share an additional folder to the guest VM. The first argument is
  # the path on the host to the actual folder. The second argument is
  # the path on the guest to mount the folder. And the optional third
  # argument is a set of non-required options.
  config.vm.synced_folder ".", "/vagrant", disabled: true
  config.vm.synced_folder "./repository", "/var/www/polygones", type: "virtualbox"

  # Enable provisioning with a shell script.
  config.vm.provision "shell", inline: <<-SHELL
    apt-get -qq update
    apt-get -qq install apt-transport-https lsb-release ca-certificates curl git zip unzip -y
    wget -O /etc/apt/trusted.gpg.d/php.gpg https://packages.sury.org/php/apt.gpg
    echo "deb https://packages.sury.org/php/ $(lsb_release -sc) main" > /etc/apt/sources.list.d/php.list
    apt-get -qq update
    apt-get purge 'php*' -qq -y
    apt-get -qq install php7.1-common -y
    apt-get -qq install php7.1 -y
    apt-get -qq install php7.1-xdebug -y
    apt-get -qq install php7.1-xml -y
    apt-get -qq install php7.1-mbstring -y
    apt-get -qq install php7.1-bcmath -y
    curl -Ss https://getcomposer.org/installer | php
    mv composer.phar /usr/bin/composer
    su vagrant
    cd /var/www/polygones
    composer install --quiet --prefer-source
    echo "cd /var/www/polygones" >> /home/vagrant/.bashrc
  SHELL
end
